import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FooterOne from "@/components/footer/FooterOne";
import FooterTwo from "@/components/footer/FooterTwo";

import HeaderOne from "@/components/header/HeaderOne";
import HeaderTwo from "@/components/header/HeaderTwo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <HeaderTwo />
        {children}
          <FooterTwo />
        </ThemeProvider>
      </body>
    </html>
  );
}
